services:
  webserver:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/usr/share/nginx/html
      - audio_input:/audio_input  # Volume condiviso
    restart: unless-stopped
  
  app:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "5000:5000"
    volumes:
      - ./py:/app  # Monta la cartella py come /app nel container
      - audio_input:/app/audio_input  # Volume condiviso mappato dentro ./py/audio_input
    working_dir: /app
    command: ["/bin/sh", "-c", "pip install elevenlabs flask && python semplice.py --api-key sk_61cddb7392d84a46443fcb7e8aebbc1673ef73ed1d412f7a"]
    restart: unless-stopped

volumes:
  audio_input:
    driver: local
    driver_opts:
      type: none
      device: ./py/audio_input
      o: bind